---
# DNS レコード（IPはvault変数を参照、ホスト名は平文で管理）
coredns_dns_records:
    - ip: '{{ coredns_vault_ip_kawashiro }}'
      hostnames:
          - kawashiro-server.kagiyama.net
          - api.kawashiro-server.kagiyama.net
    - ip: '{{ coredns_vault_ip_internal }}'
      hostnames:
          - '{{ portainer_traefik_host }}'
          - '{{ immich_traefik_host }}'
          - '{{ grafana_traefik_host }}'
          - '{{ app_traefik_host }}'
