---
- name: テスト用プレイブック
  hosts: local
  tags: test
  roles:
      - test

- name: セットアップ
  hosts: local
  tags: setup
  roles:
      - setup

- name: CoreDNS デプロイ
  hosts: local
  tags: coredns
  roles:
      - coredns

- name: Traefik デプロイ
  hosts: local
  tags: traefik
  roles:
      - traefik

- name: Portainer デプロイ
  hosts: local
  tags: portainer
  roles:
      - portainer

- name: Immich デプロイ
  hosts: local
  tags: immich
  roles:
      - immich

- name: Observability デプロイ
  hosts: local
  tags: observability
  roles:
      - observability

- name: アプリケーション デプロイ
  hosts: local
  tags: app
  roles:
      - app

- name: バックアップ設定
  hosts: local
  tags: backup
  roles:
      - backup
